import postgres from "postgres";
import { DATABASE_URL, DIRECT_DATABASE_URL } from "$app/env/private";

// Postgres through the box's connection pooler (DATABASE_URL, set by Tiffin).
// prepare: false because the pooler runs in transaction mode, where
// postgres.js's prepared statements can misbehave (docs/guide/data.md).
// One small pool per process, kept on globalThis so a dev server's hot
// reload reuses it instead of opening another.
const g = globalThis as { __sql?: postgres.Sql };
export const sql = (g.__sql ??= postgres(DATABASE_URL, { prepare: false, max: 5, idle_timeout: 20 }));

export type Note = { id: number; text: string; created_at: string };

let ready: Promise<void> | undefined;

// Creates the table once per process, on a direct connection (schema changes
// skip the pooler). Idempotent, so every deploy can run it, and serialized
// with an advisory lock so instances don't race.
export function migrate() {
  ready ??= (async () => {
    const direct = postgres(DIRECT_DATABASE_URL || DATABASE_URL, { max: 1, onnotice: () => {} });
    try {
      await direct.begin(async (tx) => {
        await tx`select pg_advisory_xact_lock(hashtext('kit-notes-migrate'))`;
        await tx`create table if not exists notes (
          id integer generated by default as identity primary key,
          text text not null check (length(text) between 1 and 280),
          created_at timestamptz not null default now()
        )`;
      });
    } finally {
      await direct.end();
    }
  })().catch((err: unknown) => {
    ready = undefined;
    throw err;
  });
  return ready;
}
