package postgres

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"
	"path/filepath"
	"slices"
	"strings"
	"testing"

	"github.com/btahir/tiffin/internal/api"
	"github.com/btahir/tiffin/internal/platform"
	"github.com/btahir/tiffin/internal/state"
	"github.com/jackc/pgx/v5"
)

// shopDB makes a database owned by a project role on an embedded Postgres,
// with a small bookshop, and returns a read-write and a read-only
// connection as that role.
func shopDB(t *testing.T) (rw, ro *pgx.Conn) {
	t.Helper()
	admin, connect := embedded(t)
	ctx := context.Background()
	for _, s := range []string{`CREATE ROLE p_shop LOGIN PASSWORD 'pw'`, `CREATE DATABASE p_shop OWNER p_shop`} {
		if _, err := admin.Exec(ctx, s); err != nil {
			t.Fatal(err)
		}
	}
	_ = connect
	role := func(readOnly bool) *pgx.Conn {
		cfg := admin.Config().Copy()
		cfg.User, cfg.Password, cfg.Database = "p_shop", "pw", "p_shop"
		if readOnly {
			cfg.RuntimeParams["default_transaction_read_only"] = "on"
		}
		c, err := pgx.ConnectConfig(ctx, cfg)
		if err != nil {
			t.Fatal(err)
		}
		t.Cleanup(func() { c.Close(context.Background()) })
		return c
	}
	rw = role(false)
	if _, err := rw.Exec(ctx, `
CREATE TYPE mood AS ENUM ('calm', 'busy');
CREATE TABLE authors (id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY, name text NOT NULL, born date);
CREATE TABLE books (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  author_id bigint REFERENCES authors(id),
  price numeric(8,2) NOT NULL DEFAULT 0 CHECK (price >= 0),
  in_stock boolean NOT NULL DEFAULT true,
  isbn text UNIQUE,
  tags text[] NOT NULL DEFAULT '{}',
  meta jsonb,
  mood mood,
  slug text GENERATED ALWAYS AS (lower(title)) STORED
);
CREATE TABLE log (at timestamptz NOT NULL DEFAULT now(), line text);
CREATE VIEW cheap AS SELECT id, title FROM books WHERE price < 10;
INSERT INTO authors (name, born) VALUES ('Ines Albrecht', '1971-03-02'), ('Tom Okafor', NULL), ('Ruth Marsh', '1980-12-24');
INSERT INTO books (title, author_id, price, isbn, tags, meta, mood) SELECT
  'Book ' || i, 1 + i % 3, (i % 40) + 0.5, CASE WHEN i % 5 = 0 THEN NULL ELSE 'isbn-' || i END,
  ARRAY['t' || (i % 3)], jsonb_build_object('pages', i * 10), CASE WHEN i % 2 = 0 THEN 'calm'::mood END
FROM generate_series(1, 250) i;
INSERT INTO log (line) VALUES ('a'), ('b');
`); err != nil {
		t.Fatal(err)
	}
	return rw, role(true)
}

func TestTableDetail(t *testing.T) {
	rw, _ := shopDB(t)
	ctx := context.Background()
	b, err := tableDetail(ctx, rw, "public", "books", true)
	if err != nil {
		t.Fatal(err)
	}
	if b.Rows != 250 || !b.RowsExact || !b.Writable || !slices.Equal(b.PrimaryKey, []string{"id"}) || b.Label != "title" || b.Managed {
		t.Fatalf("books: rows %d exact %v writable %v pk %v label %q", b.Rows, b.RowsExact, b.Writable, b.PrimaryKey, b.Label)
	}
	cats := map[string]string{}
	for _, c := range b.Columns {
		cats[c.Name] = c.Category
	}
	want := map[string]string{"id": "number", "title": "text", "author_id": "number", "price": "number", "in_stock": "bool", "isbn": "text",
		"tags": "array", "meta": "json", "mood": "enum", "slug": "text"}
	for k, v := range want {
		if cats[k] != v {
			t.Errorf("%s: category %q, want %q", k, cats[k], v)
		}
	}
	if c := b.column("mood"); !slices.Equal(c.Enum, []string{"calm", "busy"}) {
		t.Errorf("enum values: %v", c.Enum)
	}
	if c := b.column("id"); c.Identity != "by-default" || !c.Primary || c.Unique {
		t.Errorf("id: %+v", c)
	}
	if !b.column("isbn").Unique || !b.column("slug").Generated || b.column("price").Type != "numeric(8,2)" {
		t.Errorf("isbn unique, slug generated, price type: %+v %+v %+v", b.column("isbn"), b.column("slug"), b.column("price"))
	}
	if len(b.ForeignKeys) != 1 || b.ForeignKeys[0].RefTable != "authors" || !slices.Equal(b.ForeignKeys[0].Columns, []string{"author_id"}) {
		t.Errorf("foreign keys: %+v", b.ForeignKeys)
	}
	if len(b.Checks) != 1 || !strings.Contains(b.Checks[0], "price") || len(b.Indexes) != 2 {
		t.Errorf("checks %v, indexes %+v", b.Checks, b.Indexes)
	}
	a, err := tableDetail(ctx, rw, "public", "authors", true)
	if err != nil || len(a.ReferencedBy) != 1 || a.ReferencedBy[0].Table != "books" || a.column("id").Identity != "always" {
		t.Fatalf("authors: %+v %v", a, err)
	}
	l, _ := tableDetail(ctx, rw, "public", "log", true)
	if l.Writable || len(l.PrimaryKey) != 0 {
		t.Fatal("a table without a primary key is read-only")
	}
	v, _ := tableDetail(ctx, rw, "public", "cheap", true)
	if v.Kind != "view" || v.Writable {
		t.Fatalf("view: %+v", v)
	}
	_, err = tableDetail(ctx, rw, "public", "nope", true)
	var p *api.Problem
	if !errors.As(err, &p) || p.Status != 404 {
		t.Fatalf("missing table: %v", err)
	}
}

// Every page of a sorted, filtered table, in order, each row once.
func TestRowsKeysetPages(t *testing.T) {
	rw, ro := shopDB(t)
	ctx := context.Background()
	b, _ := tableDetail(ctx, rw, "public", "books", false)
	for _, sort := range [][]PGSort{nil, {{Column: "price", Desc: true}}, {{Column: "isbn"}}, {{Column: "isbn", Desc: true}}, {{Column: "mood"}, {Column: "title", Desc: true}}} {
		var got []int64
		req := PGRowsRequest{Sort: sort, Limit: 37, Filters: []PGFilter{{Column: "price", Op: "gte", Value: "5"}}, Count: true}
		var count int64
		for page := 0; ; page++ {
			r, err := queryRows(ctx, ro.PgConn(), b, req)
			if err != nil {
				t.Fatalf("sort %v page %d: %v", sort, page, err)
			}
			if page == 0 {
				count = *r.Count
			}
			for _, row := range r.Rows {
				got = append(got, row[0].(int64))
			}
			if r.Next == "" {
				break
			}
			req.After, req.Count = r.Next, false
		}
		// The same order straight from Postgres.
		order := "id"
		for i := len(sort) - 1; i >= 0; i-- {
			dir := "ASC NULLS LAST"
			if sort[i].Desc {
				dir = "DESC NULLS FIRST"
			}
			order = fmt.Sprintf("%s %s, %s", quoteIdent(sort[i].Column), dir, order)
		}
		rows, _ := rw.Query(ctx, "SELECT id FROM books WHERE price >= 5 ORDER BY "+order)
		want, err := pgx.CollectRows(rows, pgx.RowTo[int64])
		if err != nil {
			t.Fatal(err)
		}
		if !slices.Equal(got, want) || count != int64(len(want)) {
			t.Fatalf("sort %v: %d rows (count %d), want %d; first %v want %v", sort, len(got), count, len(want), got[:min(5, len(got))], want[:5])
		}
	}
}

func TestRowsFiltersAndLabels(t *testing.T) {
	rw, ro := shopDB(t)
	ctx := context.Background()
	b, _ := tableDetail(ctx, rw, "public", "books", false)
	n := func(fs ...PGFilter) int {
		t.Helper()
		r, err := queryRows(ctx, ro.PgConn(), b, PGRowsRequest{Filters: fs, Limit: 1000})
		if err != nil {
			t.Fatal(err)
		}
		return len(r.Rows)
	}
	cases := []struct {
		f    PGFilter
		want int
	}{
		{PGFilter{Column: "title", Op: "eq", Value: "Book 7"}, 1},
		{PGFilter{Column: "title", Op: "contains", Value: "ok 1"}, 111}, // 1, 10-19, 100-199
		{PGFilter{Column: "title", Op: "startsWith", Value: "book 2"}, 62},
		{PGFilter{Column: "isbn", Op: "isNull"}, 50},
		{PGFilter{Column: "isbn", Op: "notNull"}, 200},
		{PGFilter{Column: "mood", Op: "neq", Value: "calm"}, 125}, // NULLs count as different
		{PGFilter{Column: "id", Op: "in", Values: []string{"1", "2", "999"}}, 2},
		{PGFilter{Column: "in_stock", Op: "eq", Value: "true"}, 250},
		{PGFilter{Column: "title", Op: "contains", Value: "%"}, 0}, // % is a character, not a wildcard
		{PGFilter{Column: "title", Op: "eq", Value: "x'; DROP TABLE books; --"}, 0},
	}
	for _, c := range cases {
		if got := n(c.f); got != c.want {
			t.Errorf("%+v: %d rows, want %d", c.f, got, c.want)
		}
	}
	if _, err := queryRows(ctx, ro.PgConn(), b, PGRowsRequest{Filters: []PGFilter{{Column: "nope", Op: "eq"}}}); err == nil {
		t.Fatal("unknown column")
	}
	r, err := queryRows(ctx, ro.PgConn(), b, PGRowsRequest{Limit: 3})
	if err != nil {
		t.Fatal(err)
	}
	if r.Labels["author_id"]["2"] != "Tom Okafor" || r.Labels["author_id"]["3"] != "Ruth Marsh" {
		t.Fatalf("labels: %v", r.Labels)
	}
	// A table without a key pages by ctid; a view by offset.
	l, _ := tableDetail(ctx, rw, "public", "log", false)
	r, err = queryRows(ctx, ro.PgConn(), l, PGRowsRequest{Limit: 1})
	if err != nil || len(r.Rows) != 1 || r.Next == "" {
		t.Fatalf("log page 1: %+v %v", r, err)
	}
	if r, err = queryRows(ctx, ro.PgConn(), l, PGRowsRequest{Limit: 1, After: r.Next}); err != nil || len(r.Rows) != 1 || r.Rows[0][1] != "b" || r.Next != "" {
		t.Fatalf("log page 2: %+v %v", r, err)
	}
	v, _ := tableDetail(ctx, rw, "public", "cheap", false)
	r, err = queryRows(ctx, ro.PgConn(), v, PGRowsRequest{Limit: 10, Sort: []PGSort{{Column: "id"}}})
	if err != nil || len(r.Rows) != 10 || r.Next == "" {
		t.Fatalf("view: %v", err)
	}
	if r2, err := queryRows(ctx, ro.PgConn(), v, PGRowsRequest{Limit: 10, Sort: []PGSort{{Column: "id"}}, After: r.Next}); err != nil || r2.Rows[0][0].(int64) <= r.Rows[9][0].(int64) {
		t.Fatalf("view page 2: %v", err)
	}
}

func TestRowEditsAndUndo(t *testing.T) {
	rw, ro := shopDB(t)
	ctx := context.Background()
	b, _ := tableDetail(ctx, rw, "public", "books", false)
	price := func(id int) string {
		var s string
		if err := ro.QueryRow(ctx, `SELECT price::text FROM books WHERE id = $1`, id).Scan(&s); err != nil {
			return "gone"
		}
		return s
	}

	// Update, then undo.
	e, rec, res, err := updateRows(ctx, rw.PgConn(), b, []PGRowChange{{Key: map[string]any{"id": 27.0}, Values: map[string]any{"price": "24.50", "meta": map[string]any{"pages": 180.0}, "tags": []any{"a", `quo"te`}, "in_stock": false}}})
	if err != nil {
		t.Fatal(err)
	}
	if price(27) != "24.50" || !slices.Equal(e.Columns, []string{"price", "in_stock", "tags", "meta"}) || e.Keys[0] != "27" || len(res.Rows) != 1 {
		t.Fatalf("update: %s %+v", price(27), e)
	}
	var tags []string
	_ = ro.QueryRow(ctx, `SELECT tags FROM books WHERE id = 27`).Scan(&tags)
	if !slices.Equal(tags, []string{"a", `quo"te`}) {
		t.Fatalf("tags: %v", tags)
	}
	if *rec.Before[0]["price"] != "27.50" {
		t.Fatalf("before: %v", *rec.Before[0]["price"])
	}
	if _, _, _, err := undoRows(ctx, rw.PgConn(), b, e, rec, false); err != nil {
		t.Fatal(err)
	}
	var meta string
	_ = ro.QueryRow(ctx, `SELECT meta::text FROM books WHERE id = 27`).Scan(&meta)
	if price(27) != "27.50" || meta != `{"pages": 270}` {
		t.Fatalf("undo: price %s meta %s", price(27), meta)
	}

	// Undo refuses to overwrite a newer change, unless forced.
	e, rec, _, _ = updateRows(ctx, rw.PgConn(), b, []PGRowChange{{Key: map[string]any{"id": "28"}, Values: map[string]any{"price": 1.0}}})
	_, _, _, _ = updateRows(ctx, rw.PgConn(), b, []PGRowChange{{Key: map[string]any{"id": "28"}, Values: map[string]any{"price": 2.0}}})
	_, _, _, err = undoRows(ctx, rw.PgConn(), b, e, rec, false)
	var p *api.Problem
	if !errors.As(err, &p) || p.Status != 409 || price(28) != "2.00" {
		t.Fatalf("stale undo: %v, price %s", err, price(28))
	}
	if _, _, _, err := undoRows(ctx, rw.PgConn(), b, e, rec, true); err != nil || price(28) != "28.50" {
		t.Fatalf("forced undo: %v, price %s", err, price(28))
	}

	// Insert, then undo deletes it.
	e, rec, res, err = insertRow(ctx, rw.PgConn(), b, map[string]any{"title": "New", "price": 3.0})
	if err != nil || len(res.Rows) != 1 || res.Rows[0][1] != "New" {
		t.Fatalf("insert: %v %+v", err, res)
	}
	id := res.Rows[0][0].(int64)
	if _, _, _, err := undoRows(ctx, rw.PgConn(), b, e, rec, false); err != nil || price(int(id)) != "gone" {
		t.Fatalf("undo insert: %v", err)
	}

	// Delete many, then undo puts them back with their ids.
	keys := []map[string]any{}
	for i := 1; i <= 120; i++ {
		keys = append(keys, map[string]any{"id": float64(i)})
	}
	e, rec, res, err = deleteRows(ctx, rw.PgConn(), b, keys)
	if err != nil || e.Rows != 120 || len(res.Rows) != 120 || price(5) != "gone" {
		t.Fatalf("delete: %v %+v", err, e)
	}
	if _, _, _, err := undoRows(ctx, rw.PgConn(), b, e, rec, false); err != nil || price(5) != "5.50" {
		t.Fatalf("undo delete: %v %s", err, price(5))
	}
	var n int
	_ = ro.QueryRow(ctx, `SELECT count(*) FROM books`).Scan(&n)
	if n != 250 {
		t.Fatalf("%d books after undo", n)
	}

	// An identity ALWAYS key comes back as it was.
	a, _ := tableDetail(ctx, rw, "public", "authors", false)
	_, _, res, err = insertRow(ctx, rw.PgConn(), a, map[string]any{"name": "Sam Price"})
	if err != nil {
		t.Fatal(err)
	}
	id = res.Rows[0][0].(int64)
	e, rec, _, err = deleteRows(ctx, rw.PgConn(), a, []map[string]any{{"id": float64(id)}})
	if err != nil {
		t.Fatal(err)
	}
	if _, _, _, err := undoRows(ctx, rw.PgConn(), a, e, rec, false); err != nil {
		t.Fatal(err)
	}
	var name string
	if err := ro.QueryRow(ctx, `SELECT name FROM authors WHERE id = $1`, id).Scan(&name); err != nil || name != "Sam Price" {
		t.Fatalf("author %d: %q %v", id, name, err)
	}
}

func TestRowErrorsInPlainWords(t *testing.T) {
	rw, _ := shopDB(t)
	ctx := context.Background()
	b, _ := tableDetail(ctx, rw, "public", "books", false)
	a, _ := tableDetail(ctx, rw, "public", "authors", false)
	l, _ := tableDetail(ctx, rw, "public", "log", false)
	check := func(err error, status int, detail, hint string) {
		t.Helper()
		var p *api.Problem
		if !errors.As(err, &p) || p.Status != status || !strings.Contains(p.Detail, detail) || !strings.Contains(p.Hint, hint) {
			raw, _ := json.Marshal(err)
			t.Errorf("want %d %q / %q, got %s", status, detail, hint, raw)
		}
	}
	_, _, _, err := updateRows(ctx, rw.PgConn(), b, []PGRowChange{{Key: map[string]any{"id": 1.0}, Values: map[string]any{"isbn": "isbn-2"}}})
	check(err, 409, "another row already has isbn (isbn-2)", "different value")
	_, _, _, err = updateRows(ctx, rw.PgConn(), b, []PGRowChange{{Key: map[string]any{"id": 1.0}, Values: map[string]any{"title": nil}}})
	check(err, 422, "title can't be empty", "fill it in")
	_, _, _, err = updateRows(ctx, rw.PgConn(), b, []PGRowChange{{Key: map[string]any{"id": 1.0}, Values: map[string]any{"author_id": 99.0}}})
	check(err, 422, "there's no authors row with author_id (99)", "pick a row")
	_, _, _, err = deleteRows(ctx, rw.PgConn(), a, []map[string]any{{"id": 1.0}})
	check(err, 409, "rows in books still point at this row", "cascade")
	_, _, _, err = updateRows(ctx, rw.PgConn(), b, []PGRowChange{{Key: map[string]any{"id": 1.0}, Values: map[string]any{"price": "abc"}}})
	check(err, 422, "Invalid input syntax for type numeric", "enter a number")
	_, _, _, err = updateRows(ctx, rw.PgConn(), b, []PGRowChange{{Key: map[string]any{"id": 1.0}, Values: map[string]any{"price": -1.0}}})
	check(err, 422, "the value breaks the rule books_price_check", "rules")
	_, _, _, err = updateRows(ctx, rw.PgConn(), b, []PGRowChange{{Key: map[string]any{"id": 1.0}, Values: map[string]any{"slug": "x"}}})
	check(err, 422, "computed from other columns", "")
	_, _, _, err = updateRows(ctx, rw.PgConn(), a, []PGRowChange{{Key: map[string]any{"id": 1.0}, Values: map[string]any{"id": 9.0}}})
	check(err, 422, "identity column", "")
	_, _, _, err = updateRows(ctx, rw.PgConn(), b, []PGRowChange{{Key: map[string]any{"id": 9999.0}, Values: map[string]any{"price": 1.0}}})
	check(err, 404, "is gone", "reload")
	_, _, _, err = insertRow(ctx, rw.PgConn(), l, map[string]any{"line": "x"})
	check(err, 422, "has no primary key", "ADD COLUMN id")
	// A batch is all or nothing.
	_, _, _, err = updateRows(ctx, rw.PgConn(), b, []PGRowChange{
		{Key: map[string]any{"id": 3.0}, Values: map[string]any{"price": 99.0}},
		{Key: map[string]any{"id": 4.0}, Values: map[string]any{"price": "nope"}},
	})
	var s string
	_ = rw.QueryRow(ctx, `SELECT price::text FROM books WHERE id = 3`).Scan(&s)
	if err == nil || s != "3.50" {
		t.Fatalf("a failed batch must change nothing: %v %s", err, s)
	}
}

func TestCreateAndAlterTable(t *testing.T) {
	rw, _ := shopDB(t)
	ctx := context.Background()
	sql, err := createTableSQL(ctx, rw, PGTableCreate{Name: "reviews", Columns: []PGNewColumn{
		{Name: "book_id", References: &PGReference{Table: "books", OnDelete: "cascade"}},
		{Name: "stars", Type: "integer", Default: &PGDefault{Kind: "value", Value: "5"}},
		{Name: "body", Type: "text", Nullable: true},
		{Name: "tags", Type: "text[]", Default: &PGDefault{Kind: "empty-list"}},
		{Name: "at", Type: "timestamptz", Default: &PGDefault{Kind: "now"}},
		{Name: "code", Type: "text", Unique: true, Default: &PGDefault{Kind: "value", Value: "it's"}},
	}})
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{
		`CREATE TABLE "public"."reviews" (`,
		`"id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY`,
		`"book_id" bigint NOT NULL REFERENCES "public"."books" ("id") ON DELETE CASCADE`,
		`"stars" integer NOT NULL DEFAULT '5'::integer`,
		`"body" text,`,
		`"code" text NOT NULL DEFAULT 'it''s'::text UNIQUE`,
		`CREATE INDEX ON "public"."reviews" ("book_id");`,
	} {
		if !strings.Contains(sql, want) {
			t.Errorf("create SQL lacks %q:\n%s", want, sql)
		}
	}
	if err := runDDL(ctx, rw, sql); err != nil {
		t.Fatal(err)
	}
	r, _ := tableDetail(ctx, rw, "public", "reviews", true)
	if r.Rows != 0 || len(r.ForeignKeys) != 1 || r.ForeignKeys[0].OnDelete != "cascade" || len(r.Indexes) != 3 {
		t.Fatalf("reviews: %+v", r)
	}
	if err := runDDL(ctx, rw, sql); err == nil || !strings.Contains(err.Error(), "already exists") {
		t.Fatalf("twice: %v", err)
	}
	yes, no := true, false
	_, err = alterTableSQL(ctx, rw, r, PGTableAlter{
		Rename:        "book_reviews",
		RenameColumns: []PGRename{{From: "body", To: "text"}},
		DropColumns:   []string{"tags"},
		Add:           []PGNewColumn{{Name: "mood", Type: "boolean", Nullable: true}},
		Change:        []PGColumnChange{{Column: "stars", Nullable: &yes, DropDefault: true}, {Column: "code", Unique: &no}, {Column: "text", Unique: &yes}},
	})
	if err == nil {
		t.Fatal("changing a column by its new name in the same request must be refused (renames apply first, but checks use the table as it is)")
	}
	sql, err = alterTableSQL(ctx, rw, r, PGTableAlter{
		Rename:        "book_reviews",
		RenameColumns: []PGRename{{From: "body", To: "text"}},
		DropColumns:   []string{"tags"},
		Add:           []PGNewColumn{{Name: "mood", Type: "boolean", Nullable: true}},
		Change:        []PGColumnChange{{Column: "stars", Nullable: &yes, DropDefault: true}, {Column: "code", Unique: &no}},
	})
	if err != nil {
		t.Fatal(err)
	}
	if err := runDDL(ctx, rw, sql); err != nil {
		t.Fatalf("%v\n%s", err, sql)
	}
	br, err := tableDetail(ctx, rw, "public", "book_reviews", false)
	if err != nil || !br.has("text") || br.has("tags") || !br.has("mood") || !br.column("stars").Nullable || br.column("stars").Default != nil || br.column("code").Unique {
		t.Fatalf("after alter: %+v %v\n%s", br, err, sql)
	}
	if _, err := createTableSQL(ctx, rw, PGTableCreate{Name: "x", Columns: []PGNewColumn{{Name: "a"}}}); err == nil {
		t.Fatal("a column without a type")
	}
}

func TestEditLog(t *testing.T) {
	ctx := context.Background()
	db, err := state.Open(filepath.Join(t.TempDir(), "state.db"))
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()
	p := &platform.Platform{DB: db, Log: slog.Default()}
	s := "27.50"
	for i := 0; i < editKeep+5; i++ {
		e := &PGEdit{Kind: "update", Schema: "public", Table: "books", Rows: 1}
		if err := recordEdit(ctx, p, "shop", e, &editRows{Keys: []rawRow{{"id": &s}}, Before: []rawRow{{"price": &s}}, After: []rawRow{{"price": &s}}}); err != nil {
			t.Fatal(err)
		}
	}
	list, _ := listEdits(ctx, p, "shop")
	if len(list) != editKeep || !list[0].Undoable || list[0].ID <= list[1].ID {
		t.Fatalf("%d edits kept, newest first", len(list))
	}
	e, rec, err := getEdit(ctx, p, "shop", list[0].ID)
	if err != nil || *rec.Before[0]["price"] != "27.50" || e.Kind != "update" {
		t.Fatalf("get: %v %+v", err, e)
	}
	if err := markUndone(ctx, p, "shop", list[0].ID, "edit_X"); err != nil {
		t.Fatal(err)
	}
	if list, _ = listEdits(ctx, p, "shop"); list[0].UndoneBy != "edit_X" {
		t.Fatal("undone mark")
	}
	all, _ := db.KVList(ctx, nsEditRows)
	if len(all) != editKeep {
		t.Fatalf("pruned edits keep no rows: %d", len(all))
	}
}

func TestEncodeValue(t *testing.T) {
	col := func(cat string) *PGColumnDetail { return &PGColumnDetail{Name: "c", Category: cat} }
	cases := []struct {
		cat  string
		in   any
		want string
	}{
		{"text", "hi", "hi"},
		{"number", 12.5, "12.5"},
		{"number", "9007199254740993", "9007199254740993"},
		{"bool", true, "true"},
		{"json", map[string]any{"a": 1.0}, `{"a":1}`},
		{"json", "x", `"x"`},
		{"array", []any{"a", nil, `b"c`, 1.0}, `{"a",NULL,"b\"c","1"}`},
		{"array", "{x,y}", "{x,y}"},
	}
	for _, c := range cases {
		got, err := encodeValue(col(c.cat), c.in)
		if err != nil || string(got) != c.want {
			t.Errorf("%s %v → %q %v, want %q", c.cat, c.in, got, err, c.want)
		}
	}
	if b, _ := encodeValue(col("text"), nil); b != nil {
		t.Error("nil is NULL")
	}
	if _, err := encodeValue(col("text"), map[string]any{}); err == nil {
		t.Error("an object for a text column")
	}
}
