package postgres

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"math"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/btahir/tiffin/internal/api"
	"github.com/btahir/tiffin/internal/change"
	"github.com/btahir/tiffin/internal/ids"
	"github.com/btahir/tiffin/internal/platform"
	"github.com/jackc/pgx/v5/pgconn"
)

// Row edits from the table editor: insert, update and delete by primary key.
// Each one records the rows as they were (Postgres's own text, so writing
// them back is exact), which is what Undo writes back. Single edits take no
// snapshot; deleting more than bulkDelete rows takes one first.

// bulkDelete is how many rows one delete may remove before a snapshot is taken first.
const bulkDelete = 100

// PGRowChange is one row's new values, found by its primary key.
type PGRowChange struct {
	Key    map[string]any `json:"key" doc:"The row's primary key: column → value"`
	Values map[string]any `json:"values" doc:"Column → new value. JSON columns take any JSON; arrays take a JSON array; null is NULL."`
}

// PGEdit is a recorded row edit: what changed, by whom, and whether it was undone.
type PGEdit struct {
	ID       string       `json:"id" doc:"Edit ID (edit_...)"`
	At       time.Time    `json:"at"`
	Actor    change.Actor `json:"actor"`
	Branch   string       `json:"branch,omitempty"`
	Schema   string       `json:"schema"`
	Table    string       `json:"table"`
	Kind     string       `json:"kind" enum:"insert,update,delete"`
	Rows     int          `json:"rows" doc:"How many rows it touched"`
	Columns  []string     `json:"columns,omitempty" doc:"For updates: the columns that changed"`
	Keys     []string     `json:"keys,omitempty" doc:"The touched rows' keys, as text (the first 20)"`
	Snapshot string       `json:"snapshot,omitempty" doc:"Snapshot taken first (deletes of more than 100 rows)"`
	Undoable bool         `json:"undoable" doc:"Its old rows are kept, so it can be undone"`
	UndoOf   string       `json:"undoOf,omitempty" doc:"The edit this one undid"`
	UndoneBy string       `json:"undoneBy,omitempty"`
}

// PGEditResult is an edit and the rows it wrote (or, for a delete, removed).
type PGEditResult struct {
	Edit    PGEdit     `json:"edit"`
	Columns []PGColumn `json:"columns"`
	Rows    [][]any    `json:"rows"`
}

// rawRow is a row in Postgres's text form; a nil value is NULL.
type rawRow map[string]*string

// editRows is what Undo needs: the key of each row after the edit, and its
// columns before and after.
type editRows struct {
	Keys   []rawRow `json:"keys"`
	Before []rawRow `json:"before,omitempty"`
	After  []rawRow `json:"after,omitempty"`
}

// errNoKey refuses row edits on a table without a primary key.
func errNoKey(t *PGTableDetail) error {
	if t.Kind != "table" && t.Kind != "partitioned" {
		return api.NewProblem(422, "validation", fmt.Sprintf("%s is a %s: change the tables it reads from instead", t.slug(), strings.ReplaceAll(t.Kind, "-", " ")))
	}
	p := api.NewProblem(422, "validation", fmt.Sprintf("%s has no primary key, so its rows can't be told apart to edit one", t.slug()))
	p.Hint = "add one, e.g. `ALTER TABLE " + t.ident() + " ADD COLUMN id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY`, or change rows with sql write"
	return p
}

// encodeValue turns a JSON value into the text Postgres parses for col.
func encodeValue(col *PGColumnDetail, v any) ([]byte, error) {
	if v == nil {
		return nil, nil
	}
	if col.Category == "json" {
		return json.Marshal(v)
	}
	if col.Category == "array" {
		if s, ok := v.(string); ok {
			return []byte(s), nil // an array literal, {a,b}
		}
		list, ok := v.([]any)
		if !ok {
			return nil, fmt.Errorf("%s takes a list", col.Name)
		}
		return []byte(arrayLiteral(list)), nil
	}
	switch x := v.(type) {
	case string:
		return []byte(x), nil
	case bool:
		return []byte(strconv.FormatBool(x)), nil
	case float64:
		if math.IsInf(x, 0) || math.IsNaN(x) {
			return nil, fmt.Errorf("%s: not a number", col.Name)
		}
		return []byte(strconv.FormatFloat(x, 'f', -1, 64)), nil
	case json.Number:
		return []byte(x.String()), nil
	}
	return nil, fmt.Errorf("%s takes text, a number or true/false, not %T", col.Name, v)
}

// arrayLiteral writes a Postgres array literal: {"a","b",NULL}.
func arrayLiteral(list []any) string {
	var b strings.Builder
	b.WriteByte('{')
	for i, v := range list {
		if i > 0 {
			b.WriteByte(',')
		}
		switch x := v.(type) {
		case nil:
			b.WriteString("NULL")
		case []any:
			b.WriteString(arrayLiteral(x))
		default:
			var s string
			switch y := x.(type) {
			case string:
				s = y
			case bool:
				s = strconv.FormatBool(y)
			case float64:
				s = strconv.FormatFloat(y, 'f', -1, 64)
			default:
				raw, _ := json.Marshal(y)
				s = string(raw)
			}
			b.WriteByte('"')
			b.WriteString(strings.NewReplacer(`\`, `\\`, `"`, `\"`).Replace(s))
			b.WriteByte('"')
		}
	}
	b.WriteByte('}')
	return b.String()
}

// keyWhere is "pk1 = $n AND pk2 = $m" for a row's key.
func keyWhere(t *PGTableDetail, key map[string]any, ps *params) (string, error) {
	if len(key) != len(t.PrimaryKey) {
		return "", api.NewProblem(422, "validation", fmt.Sprintf("key must give exactly the primary key of %s: %s", t.slug(), strings.Join(t.PrimaryKey, ", ")))
	}
	conds := make([]string, len(t.PrimaryKey))
	for i, k := range t.PrimaryKey {
		v, ok := key[k]
		if !ok || v == nil {
			return "", api.NewProblem(422, "validation", fmt.Sprintf("key lacks %s", k))
		}
		b, err := encodeValue(t.column(k), v)
		if err != nil {
			return "", api.NewProblem(422, "validation", err.Error())
		}
		conds[i] = fmt.Sprintf("%s = %s", quoteIdent(k), ps.add(b))
	}
	return strings.Join(conds, " AND "), nil
}

// rawKeyWhere is keyWhere for a recorded key.
func rawKeyWhere(t *PGTableDetail, key rawRow, ps *params) string {
	conds := make([]string, len(t.PrimaryKey))
	for i, k := range t.PrimaryKey {
		conds[i] = fmt.Sprintf("%s = %s", quoteIdent(k), ps.add(rawBytes(key[k])))
	}
	return strings.Join(conds, " AND ")
}

func rawBytes(s *string) []byte {
	if s == nil {
		return nil
	}
	return []byte(*s)
}

// writable checks the columns being written exist and can be written.
func writable(t *PGTableDetail, values map[string]any) error {
	for name := range values {
		if !t.has(name) {
			return api.NewProblem(422, "validation", fmt.Sprintf("%s has no column %q", t.slug(), name))
		}
		c := t.column(name)
		if c.Generated {
			return api.NewProblem(422, "validation", fmt.Sprintf("%s is computed from other columns, so it can't be set", name))
		}
	}
	return nil
}

// sortedKeys returns m's keys in table order.
func (t *PGTableDetail) ordered(m map[string]any) []string {
	var out []string
	for _, c := range t.Columns {
		if _, ok := m[c.Name]; ok {
			out = append(out, c.Name)
		}
	}
	return out
}

// rowsResult turns raw rows read with t's select list into the API's rows.
func rowsResult(fields []pgconn.FieldDescription, raw [][][]byte) ([]PGColumn, [][]any) {
	cols := make([]PGColumn, len(fields))
	for i, f := range fields {
		cols[i] = PGColumn{Name: f.Name, Type: typeName(f.DataTypeOID)}
	}
	rows := make([][]any, len(raw))
	for i, r := range raw {
		row := make([]any, len(fields))
		for j := range fields {
			row[j] = textValue(fields[j], r[j])
		}
		rows[i] = row
	}
	return cols, rows
}

// toRaw keeps the named columns of a raw row (all of them when names is nil).
func toRaw(t *PGTableDetail, r [][]byte, names []string) rawRow {
	out := rawRow{}
	for i, c := range t.Columns {
		if names != nil && !contains(names, c.Name) {
			continue
		}
		if r[i] != nil {
			s := string(r[i])
			out[c.Name] = &s
		} else {
			out[c.Name] = nil
		}
	}
	return out
}

func contains(list []string, s string) bool {
	for _, x := range list {
		if x == s {
			return true
		}
	}
	return false
}

func (t *PGTableDetail) keyText(r rawRow) string {
	parts := make([]string, len(t.PrimaryKey))
	for i, k := range t.PrimaryKey {
		if v := r[k]; v != nil {
			parts[i] = *v
		}
	}
	return strings.Join(parts, ", ")
}

// tx runs f in a transaction on pc.
func tx(ctx context.Context, pc *pgconn.PgConn, f func() error) error {
	if err := pc.Exec(ctx, "BEGIN").Close(); err != nil {
		return err
	}
	if err := f(); err != nil {
		_ = pc.Exec(context.WithoutCancel(ctx), "ROLLBACK").Close()
		return err
	}
	return pc.Exec(ctx, "COMMIT").Close()
}

// insertRow adds one row and returns it as stored.
func insertRow(ctx context.Context, pc *pgconn.PgConn, t *PGTableDetail, values map[string]any) (*PGEdit, *editRows, *PGEditResult, error) {
	if !t.Writable {
		return nil, nil, nil, errNoKey(t)
	}
	if err := writable(t, values); err != nil {
		return nil, nil, nil, err
	}
	ps := &params{}
	names := t.ordered(values)
	q := fmt.Sprintf("INSERT INTO %s DEFAULT VALUES RETURNING %s", t.ident(), t.selectList())
	if len(names) > 0 {
		cols, ph := make([]string, len(names)), make([]string, len(names))
		for i, n := range names {
			b, err := encodeValue(t.column(n), values[n])
			if err != nil {
				return nil, nil, nil, api.NewProblem(422, "validation", err.Error())
			}
			cols[i], ph[i] = quoteIdent(n), ps.add(b)
		}
		over := ""
		for _, n := range names {
			if t.column(n).Identity == "always" {
				over = " OVERRIDING SYSTEM VALUE"
			}
		}
		q = fmt.Sprintf("INSERT INTO %s (%s)%s VALUES (%s) RETURNING %s", t.ident(), strings.Join(cols, ", "), over, strings.Join(ph, ", "), t.selectList())
	}
	fields, raw, err := readAll(pc.ExecParams(ctx, q, ps.args, nil, nil, nil))
	if err != nil {
		return nil, nil, nil, rowError(err, t, "insert")
	}
	after := toRaw(t, raw[0], nil)
	rec := &editRows{Keys: []rawRow{toRaw(t, raw[0], t.PrimaryKey)}, After: []rawRow{after}}
	e := &PGEdit{Kind: "insert", Rows: 1, Keys: []string{t.keyText(after)}}
	cols, rows := rowsResult(fields, raw)
	return e, rec, &PGEditResult{Columns: cols, Rows: rows}, nil
}

// updateRows changes rows by key, in one transaction, and records what
// the changed columns held before.
func updateRows(ctx context.Context, pc *pgconn.PgConn, t *PGTableDetail, changes []PGRowChange) (*PGEdit, *editRows, *PGEditResult, error) {
	if !t.Writable {
		return nil, nil, nil, errNoKey(t)
	}
	rec := &editRows{}
	e := &PGEdit{Kind: "update", Rows: len(changes)}
	var fields []pgconn.FieldDescription
	var all [][][]byte
	changed := map[string]bool{}
	err := tx(ctx, pc, func() error {
		for _, ch := range changes {
			if len(ch.Values) == 0 {
				return api.NewProblem(422, "validation", "values is empty: nothing to change")
			}
			if err := writable(t, ch.Values); err != nil {
				return err
			}
			names := t.ordered(ch.Values)
			for _, n := range names {
				if t.column(n).Identity == "always" {
					return api.NewProblem(422, "validation", fmt.Sprintf("%s is numbered by Postgres (an identity column), so it can't be changed", n))
				}
			}
			ps := &params{}
			where, err := keyWhere(t, ch.Key, ps)
			if err != nil {
				return err
			}
			_, before, err := readAll(pc.ExecParams(ctx, fmt.Sprintf("SELECT %s FROM %s WHERE %s FOR UPDATE", t.selectList(), t.ident(), where), ps.args, nil, nil, nil))
			if err != nil {
				return rowError(err, t, "update")
			}
			if len(before) == 0 {
				return rowGone(t, ch.Key)
			}
			sets := make([]string, len(names))
			for i, n := range names {
				b, err := encodeValue(t.column(n), ch.Values[n])
				if err != nil {
					return api.NewProblem(422, "validation", err.Error())
				}
				sets[i] = fmt.Sprintf("%s = %s", quoteIdent(n), ps.add(b))
				changed[n] = true
			}
			f, after, err := readAll(pc.ExecParams(ctx, fmt.Sprintf("UPDATE %s SET %s WHERE %s RETURNING %s", t.ident(), strings.Join(sets, ", "), where, t.selectList()), ps.args, nil, nil, nil))
			if err != nil {
				return rowError(err, t, "update")
			}
			fields = f
			all = append(all, after...)
			rec.Keys = append(rec.Keys, toRaw(t, after[0], t.PrimaryKey))
			rec.Before = append(rec.Before, toRaw(t, before[0], names))
			rec.After = append(rec.After, toRaw(t, after[0], names))
			if len(e.Keys) < 20 {
				e.Keys = append(e.Keys, t.keyText(rec.Keys[len(rec.Keys)-1]))
			}
		}
		return nil
	})
	if err != nil {
		return nil, nil, nil, err
	}
	for _, c := range t.Columns {
		if changed[c.Name] {
			e.Columns = append(e.Columns, c.Name)
		}
	}
	cols, rows := rowsResult(fields, all)
	return e, rec, &PGEditResult{Columns: cols, Rows: rows}, nil
}

// deleteRows removes rows by key and returns them.
func deleteRows(ctx context.Context, pc *pgconn.PgConn, t *PGTableDetail, keys []map[string]any) (*PGEdit, *editRows, *PGEditResult, error) {
	if !t.Writable {
		return nil, nil, nil, errNoKey(t)
	}
	rec := &editRows{}
	var fields []pgconn.FieldDescription
	var all [][][]byte
	err := tx(ctx, pc, func() error {
		for start := 0; start < len(keys); start += 500 {
			ps := &params{}
			var ors []string
			for _, k := range keys[start:min(start+500, len(keys))] {
				w, err := keyWhere(t, k, ps)
				if err != nil {
					return err
				}
				ors = append(ors, "("+w+")")
			}
			f, gone, err := readAll(pc.ExecParams(ctx, fmt.Sprintf("DELETE FROM %s WHERE %s RETURNING %s", t.ident(), strings.Join(ors, " OR "), t.selectList()), ps.args, nil, nil, nil))
			if err != nil {
				return rowError(err, t, "delete")
			}
			fields = f
			all = append(all, gone...)
		}
		if len(all) == 0 {
			return api.NewProblem(404, "not_found", "those rows are already gone")
		}
		return nil
	})
	if err != nil {
		return nil, nil, nil, err
	}
	e := &PGEdit{Kind: "delete", Rows: len(all)}
	for _, r := range all {
		row := toRaw(t, r, nil)
		rec.Keys = append(rec.Keys, toRaw(t, r, t.PrimaryKey))
		rec.Before = append(rec.Before, row)
		if len(e.Keys) < 20 {
			e.Keys = append(e.Keys, t.keyText(row))
		}
	}
	cols, rows := rowsResult(fields, all)
	return e, rec, &PGEditResult{Columns: cols, Rows: rows}, nil
}

// undoRows writes back what an edit replaced: an insert's row is deleted,
// an update's old values return, a delete's rows come back. An update is
// refused (409) when the row changed again since, unless force.
func undoRows(ctx context.Context, pc *pgconn.PgConn, t *PGTableDetail, e *PGEdit, rec *editRows, force bool) (*PGEdit, *editRows, *PGEditResult, error) {
	switch e.Kind {
	case "insert":
		keys := make([]map[string]any, len(rec.Keys))
		for i, k := range rec.Keys {
			keys[i] = rawKey(k)
		}
		ue, ur, res, err := deleteRows(ctx, pc, t, keys)
		var p *api.Problem
		if errors.As(err, &p) && p.Status == 404 {
			return nil, nil, nil, api.NewProblem(409, "conflict", "the row it added is already gone")
		}
		return ue, ur, res, err
	case "update":
		changes := make([]PGRowChange, len(rec.Keys))
		err := tx(ctx, pc, func() error {
			for i, k := range rec.Keys {
				ps := &params{}
				names := make([]string, 0, len(rec.After[i]))
				for _, c := range t.Columns {
					if _, ok := rec.After[i][c.Name]; ok {
						names = append(names, c.Name)
					}
				}
				cols := make([]string, len(names))
				for j, n := range names {
					cols[j] = quoteIdent(n) + "::text"
				}
				_, now, err := readAll(pc.ExecParams(ctx, fmt.Sprintf("SELECT %s FROM %s WHERE %s FOR UPDATE", strings.Join(cols, ", "), t.ident(), rawKeyWhere(t, k, ps)), ps.args, nil, nil, nil))
				if err != nil {
					return rowError(err, t, "update")
				}
				if len(now) == 0 {
					return api.NewProblem(409, "conflict", fmt.Sprintf("row %s is gone, so there is nothing to put back", t.keyText(k)))
				}
				for j, n := range names {
					if !force && !sameText(now[0][j], rec.After[i][n]) {
						p := api.NewProblem(409, "conflict", fmt.Sprintf("%s on row %s changed again since; undoing would overwrite that", n, t.keyText(k)))
						p.Hint = "reload to see it, or undo with force to put the old value back anyway"
						return p
					}
				}
				vals := map[string]any{}
				for n, v := range rec.Before[i] {
					if v == nil {
						vals[n] = nil
					} else {
						vals[n] = *v
					}
				}
				changes[i] = PGRowChange{Key: rawKey(k), Values: vals}
			}
			return nil
		})
		if err != nil {
			return nil, nil, nil, err
		}
		return updateRawRows(ctx, pc, t, changes)
	case "delete":
		return reinsertRows(ctx, pc, t, rec.Before)
	}
	return nil, nil, nil, fmt.Errorf("unknown edit kind %q", e.Kind)
}

// updateRawRows is updateRows for values in Postgres's text form (strings
// even for JSON and arrays), as Undo writes them.
func updateRawRows(ctx context.Context, pc *pgconn.PgConn, t *PGTableDetail, changes []PGRowChange) (*PGEdit, *editRows, *PGEditResult, error) {
	raw := *t
	raw.Columns = make([]PGColumnDetail, len(t.Columns))
	for i, c := range t.Columns {
		c.Category = "text" // send the stored text as it is
		c.Identity = ""
		raw.Columns[i] = c
	}
	e, rec, res, err := updateRows(ctx, pc, &raw, changes)
	if e != nil {
		e.Columns = nil
		for _, c := range t.Columns {
			for n := range changes[0].Values {
				if n == c.Name {
					e.Columns = append(e.Columns, n)
				}
			}
		}
	}
	return e, rec, res, err
}

// reinsertRows puts deleted rows back exactly, keys and identity values included.
func reinsertRows(ctx context.Context, pc *pgconn.PgConn, t *PGTableDetail, rows []rawRow) (*PGEdit, *editRows, *PGEditResult, error) {
	var names []string
	over := ""
	for _, c := range t.Columns {
		if c.Generated {
			continue
		}
		names = append(names, c.Name)
		if c.Identity == "always" {
			over = " OVERRIDING SYSTEM VALUE"
		}
	}
	cols := make([]string, len(names))
	for i, n := range names {
		cols[i] = quoteIdent(n)
	}
	rec := &editRows{}
	var fields []pgconn.FieldDescription
	var all [][][]byte
	err := tx(ctx, pc, func() error {
		for start := 0; start < len(rows); start += 200 {
			ps := &params{}
			var tuples []string
			for _, r := range rows[start:min(start+200, len(rows))] {
				ph := make([]string, len(names))
				for i, n := range names {
					ph[i] = ps.add(rawBytes(r[n]))
				}
				tuples = append(tuples, "("+strings.Join(ph, ", ")+")")
			}
			f, back, err := readAll(pc.ExecParams(ctx, fmt.Sprintf("INSERT INTO %s (%s)%s VALUES %s RETURNING %s", t.ident(), strings.Join(cols, ", "), over, strings.Join(tuples, ", "), t.selectList()), ps.args, nil, nil, nil))
			if err != nil {
				return rowError(err, t, "insert")
			}
			fields = f
			all = append(all, back...)
		}
		return nil
	})
	if err != nil {
		return nil, nil, nil, err
	}
	e := &PGEdit{Kind: "insert", Rows: len(all)}
	for _, r := range all {
		row := toRaw(t, r, nil)
		rec.Keys = append(rec.Keys, toRaw(t, r, t.PrimaryKey))
		rec.After = append(rec.After, row)
		if len(e.Keys) < 20 {
			e.Keys = append(e.Keys, t.keyText(row))
		}
	}
	c, out := rowsResult(fields, all)
	return e, rec, &PGEditResult{Columns: c, Rows: out}, nil
}

func rawKey(k rawRow) map[string]any {
	out := map[string]any{}
	for n, v := range k {
		if v != nil {
			out[n] = *v
		}
	}
	return out
}

func sameText(now []byte, then *string) bool {
	if now == nil || then == nil {
		return now == nil && then == nil
	}
	return string(now) == *then
}

func rowGone(t *PGTableDetail, key map[string]any) error {
	parts := make([]string, 0, len(t.PrimaryKey))
	for _, k := range t.PrimaryKey {
		parts = append(parts, fmt.Sprint(key[k]))
	}
	p := api.NewProblem(404, "not_found", fmt.Sprintf("row %s of %s is gone (deleted since you loaded it)", strings.Join(parts, ", "), t.slug()))
	p.Hint = "reload the table"
	return p
}

// rowError says a Postgres error about a row in plain words, with the fix.
// The SQLSTATE stays in the title for agents.
func rowError(err error, t *PGTableDetail, verb string) error {
	var pe *pgconn.PgError
	if !errors.As(err, &pe) {
		return err
	}
	p := api.NewProblem(422, "validation", "")
	p.Title = "Postgres error " + pe.Code
	col := pe.ColumnName
	key, val := keyDetail(pe.Detail)
	switch pe.Code {
	case "23505":
		p.Status, p.Code = 409, "conflict"
		p.Detail = fmt.Sprintf("another row already has %s %s", orWord(key, "that value"), quoted(val))
		p.Hint = "use a different value, or change the other row first"
	case "23502":
		p.Detail = fmt.Sprintf("%s can't be empty", orWord(col, "a column"))
		p.Hint = "fill it in, or allow empty values in the column's settings"
	case "23503":
		if verb == "delete" || strings.Contains(pe.Detail, "still referenced") {
			p.Status, p.Code = 409, "conflict"
			p.Detail = fmt.Sprintf("rows in %s still point at this row", orWord(between(pe.Detail, `from table "`, `"`), "another table"))
			p.Hint = "delete or change those rows first, or make the link remove them too (on delete cascade)"
		} else {
			p.Detail = fmt.Sprintf("there's no %s row with %s %s", orWord(between(pe.Detail, `in table "`, `"`), "linked"), orWord(key, "that key"), quoted(val))
			p.Hint = "pick a row that exists"
		}
	case "22P02", "22007", "22008", "22003", "22001", "22023":
		p.Detail = sentenceCase(pe.Message)
		if col != "" {
			p.Detail += " (" + col + ")"
		}
		switch {
		case strings.Contains(pe.Message, "integer") || strings.Contains(pe.Message, "bigint") || strings.Contains(pe.Message, "smallint"):
			p.Hint = "enter a whole number, like 42"
		case strings.Contains(pe.Message, "numeric") || strings.Contains(pe.Message, "double") || strings.Contains(pe.Message, "real"):
			p.Hint = "enter a number, like 12.50"
		case strings.Contains(pe.Message, "boolean"):
			p.Hint = "use true or false"
		case strings.Contains(pe.Message, "uuid"):
			p.Hint = "a UUID looks like 0b9e3a6c-6f2e-4d1a-9b8e-2f9d1c3a4b5c"
		case strings.Contains(pe.Message, "date") || strings.Contains(pe.Message, "time"):
			p.Hint = "write dates as 2026-10-05 and times as 2026-10-05 14:30"
		case strings.Contains(pe.Message, "json"):
			p.Hint = "check the JSON: keys and text in double quotes, no trailing commas"
		case pe.Code == "22001":
			p.Hint = "shorten it, or allow longer values in the column's type"
		case strings.Contains(pe.Message, "enum"):
			p.Hint = "pick one of the column's values"
		}
	case "23514":
		p.Detail = fmt.Sprintf("the value breaks the rule %s", orWord(pe.ConstraintName, "on this table"))
		p.Hint = "see the table's rules under Structure, and pick a value that keeps them"
	case "42501":
		p.Status, p.Code = 403, "forbidden"
		p.Detail = fmt.Sprintf("your project's database role may not %s rows in %s", verb, t.slug())
		p.Hint = "managed tables change through their own pages (sign-in through Users)"
	case "57014":
		p.Detail = "it took too long and was stopped"
		p.Hint = "try fewer rows at once"
	case "40P01", "55P03":
		p.Status, p.Code = 409, "conflict"
		p.Detail = "another change to these rows was in progress"
		p.Hint = "try again in a moment"
	default:
		return sqlError(err)
	}
	return p
}

// keyDetail reads "Key (email)=(a@b.c) already exists." into its parts.
func keyDetail(detail string) (key, val string) {
	return between(detail, "Key (", ")="), between(detail, ")=(", ")")
}

func between(s, a, b string) string {
	i := strings.Index(s, a)
	if i < 0 {
		return ""
	}
	s = s[i+len(a):]
	if j := strings.Index(s, b); j >= 0 {
		return s[:j]
	}
	return ""
}

func orWord(s, alt string) string {
	if s == "" {
		return alt
	}
	return s
}

func quoted(s string) string {
	if s == "" {
		return ""
	}
	return "(" + clip(s, 80) + ")"
}

func sentenceCase(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

// ---- the edit log ----

// Edits are kept in the box's state: per project, the newest editKeep for
// SnapshotKeep, each edit's rows under its own key.
const (
	nsEdits    = "postgres.edits"     // project → JSON []PGEdit, newest first
	nsEditRows = "postgres.edit-rows" // edit ID → JSON editRows
	editKeep   = 200
	// editRowsMax is the most old-row data an edit keeps; past it the edit
	// can't be undone (bulk deletes have their snapshot).
	editRowsMax = 32 << 20
)

var editsMu sync.Mutex

func listEdits(ctx context.Context, p *platform.Platform, project string) ([]PGEdit, error) {
	raw, ok, err := p.DB.KVGet(ctx, nsEdits, project)
	if err != nil || !ok {
		return []PGEdit{}, err
	}
	var out []PGEdit
	if err := json.Unmarshal(raw, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// recordEdit stores e (and its rows, when they fit) and prunes old edits.
func recordEdit(ctx context.Context, p *platform.Platform, project string, e *PGEdit, rec *editRows) error {
	editsMu.Lock()
	defer editsMu.Unlock()
	e.ID, e.At = ids.New("edit"), time.Now().UTC()
	if rec != nil {
		raw, err := json.Marshal(rec)
		if err != nil {
			return err
		}
		if len(raw) <= editRowsMax {
			if err := p.DB.KVPut(ctx, nsEditRows, e.ID, raw); err != nil {
				return err
			}
			e.Undoable = true
		}
	}
	list, err := listEdits(ctx, p, project)
	if err != nil {
		return err
	}
	list = append([]PGEdit{*e}, list...)
	keep := list[:0]
	for i, x := range list {
		if i < editKeep && time.Since(x.At) < SnapshotKeep {
			keep = append(keep, x)
		} else {
			_ = p.DB.KVDelete(ctx, nsEditRows, x.ID)
		}
	}
	return saveEdits(ctx, p, project, keep)
}

func saveEdits(ctx context.Context, p *platform.Platform, project string, list []PGEdit) error {
	raw, err := json.Marshal(list)
	if err != nil {
		return err
	}
	return p.DB.KVPut(ctx, nsEdits, project, raw)
}

// getEdit returns an edit and its rows.
func getEdit(ctx context.Context, p *platform.Platform, project, id string) (*PGEdit, *editRows, error) {
	list, err := listEdits(ctx, p, project)
	if err != nil {
		return nil, nil, err
	}
	for _, e := range list {
		if e.ID != id {
			continue
		}
		if !e.Undoable {
			return &e, nil, nil
		}
		raw, ok, err := p.DB.KVGet(ctx, nsEditRows, id)
		if err != nil {
			return nil, nil, err
		}
		if !ok {
			return &e, nil, nil
		}
		var rec editRows
		if err := json.Unmarshal(raw, &rec); err != nil {
			return nil, nil, err
		}
		return &e, &rec, nil
	}
	return nil, nil, api.NewProblem(404, "not_found", "no edit "+id+" in project "+project+" (edits are kept for 7 days)")
}

// markUndone links an edit to the edit that undid it.
func markUndone(ctx context.Context, p *platform.Platform, project, id, by string) error {
	editsMu.Lock()
	defer editsMu.Unlock()
	list, err := listEdits(ctx, p, project)
	if err != nil {
		return err
	}
	for i := range list {
		if list[i].ID == id {
			list[i].UndoneBy = by
		}
	}
	return saveEdits(ctx, p, project, list)
}
