#!/usr/bin/env bash
# Seeds a dev box (tiffin up, with services) for the Database console specs
# (db-*.spec.ts): a bookshop with links between tables, an enum, JSON, a list
# column, a composite key, a table without a key, a view, 50,000 events for
# the grid's speed, and a "warehouse" project with 34 linked tables for the
# schema diagram.
#
#   TIFFIN_CONFIG_DIR=/tmp/tiffin-dev-db e2e/seed-box-db.sh <tiffin binary>
#
# Throwaway boxes only: it applies configs and writes data.
set -euo pipefail
BIN="${1:?usage: seed-box-db.sh <tiffin binary>}"
: "${TIFFIN_CONFIG_DIR:?point TIFFIN_CONFIG_DIR at a dev box}"
CFG="$TIFFIN_CONFIG_DIR/boxes.json"
URL="$(jq -r '.boxes[.current].url' "$CFG")"
OWNER="$(jq -r '.boxes[.current].token' "$CFG")"
CA="$(jq -r '.boxes[.current].caFile' "$CFG")"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

api() { # api METHOD PATH [JSON]
  local m="$1" p="$2"
  shift 2
  curl -fsS --cacert "$CA" -X "$m" -H "Authorization: Bearer $OWNER" -H 'Content-Type: application/json' ${1:+-d "$1"} "$URL$p"
}
sql() { # sql <project> <statements>
  api POST "/v1/projects/$1/sql/write" "$(jq -nc --arg s "$2" '{sql:$s, timeoutSeconds:120}')" >/dev/null
}
apply() { # apply <dir> <intent>
  local hash
  hash="$("$BIN" plan "$1" --json | jq -r .hash)"
  "$BIN" apply "$1" --confirm "$hash" -m "$2" --json >/dev/null
}
wait_ready() {
  for _ in $(seq 1 90); do
    if api GET "/v1/projects/$1" | jq -e '[.status[]?.state] | all(. == "ready")' >/dev/null; then return 0; fi
    sleep 2
  done
  echo "project $1 is not ready" >&2
  return 1
}

for p in bookshop warehouse; do
  mkdir -p "$WORK/$p"
  printf 'import { defineConfig } from "tiffin-sdk";\nexport default defineConfig({ project: "%s", services: { postgres: {} } });\n' "$p" >"$WORK/$p/tiffin.config.ts"
  apply "$WORK/$p" "Start $p with a database"
done
wait_ready bookshop
wait_ready warehouse

sql bookshop "
CREATE TYPE book_format AS ENUM ('hardback', 'paperback', 'ebook');
CREATE TYPE order_status AS ENUM ('paid', 'shipped', 'refunded');
CREATE TABLE authors (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name text NOT NULL, born date, country text);
CREATE TABLE books (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  author_id bigint REFERENCES authors(id),
  price numeric(8,2) NOT NULL DEFAULT 0 CHECK (price >= 0),
  in_stock boolean NOT NULL DEFAULT true,
  format book_format NOT NULL DEFAULT 'paperback',
  published date,
  tags text[] NOT NULL DEFAULT '{}',
  meta jsonb
);
CREATE TABLE customers (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), email text NOT NULL UNIQUE, name text NOT NULL, city text, joined_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE orders (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, customer_id uuid NOT NULL REFERENCES customers(id), status order_status NOT NULL DEFAULT 'paid', placed_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE order_items (order_id bigint NOT NULL REFERENCES orders(id) ON DELETE CASCADE, book_id bigint NOT NULL REFERENCES books(id), qty int NOT NULL DEFAULT 1, PRIMARY KEY (order_id, book_id));
CREATE TABLE reviews (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, book_id bigint NOT NULL REFERENCES books(id) ON DELETE CASCADE, stars int NOT NULL CHECK (stars BETWEEN 1 AND 5), body text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE events (id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY, kind text NOT NULL, at timestamptz NOT NULL, payload jsonb);
CREATE TABLE import_log (at timestamptz NOT NULL DEFAULT now(), line text);
CREATE INDEX ON books (author_id);
CREATE INDEX ON orders (customer_id);
CREATE INDEX ON reviews (book_id);
"
sql bookshop "
INSERT INTO authors (name, born, country) VALUES
  ('Ines Albrecht', '1971-03-02', 'Germany'), ('Tom Okafor', '1984-07-19', 'Nigeria'), ('Ruth Marsh', '1966-11-30', 'England'),
  ('Sam Price', NULL, 'Wales'), ('Mei Tanaka', '1990-01-08', 'Japan'), ('Lucas Moreau', '1979-05-14', 'France'),
  ('Amara Silva', '1988-09-21', 'Portugal'), ('Jonas Berg', '1975-02-27', 'Norway');
INSERT INTO books (title, author_id, price, in_stock, format, published, tags, meta) VALUES
  ('A Field Guide to Moss', 1, 18.00, true, 'hardback', '2019-04-11', '{nature,guides}', '{\"pages\": 212, \"isbn\": \"978-0-9550-0012\"}'),
  ('Bread & Weather', 2, 24.50, true, 'paperback', '2021-09-02', '{food}', '{\"pages\": 180, \"isbn\": \"978-0-9550-0029\"}'),
  ('Small Engines', 3, 12.99, true, 'paperback', '2015-01-20', '{repair}', '{\"pages\": 96}'),
  ('The Quiet Harbour', 1, 21.00, true, 'hardback', '2023-06-15', '{fiction}', '{\"pages\": 340}'),
  ('Notes on Clay', 4, 9.50, true, 'ebook', '2020-03-03', '{craft,ceramics}', '{\"pages\": 120}'),
  ('Salt Roads', 5, 16.00, false, 'paperback', '2018-08-08', '{history}', '{\"pages\": 288}'),
  ('Winter Kitchen', 2, 27.00, true, 'hardback', '2024-11-01', '{food,seasonal}', '{\"pages\": 256}'),
  ('Paper Boats', 6, 8.99, true, 'ebook', '2017-05-30', '{fiction,short}', NULL),
  ('Tidelines', 7, 14.25, true, 'paperback', '2022-02-14', '{nature}', '{\"pages\": 198}'),
  ('North of Nowhere', 8, 19.75, false, 'hardback', '2016-10-10', '{travel}', '{\"pages\": 310}');
INSERT INTO books (title, author_id, price, in_stock, format, published, tags, meta)
SELECT initcap((ARRAY['the','a','small','quiet','long','last','green','salt','paper','winter'])[1 + i % 10] || ' ' ||
       (ARRAY['garden','river','letters','harbour','engine','kitchen','map','orchard','lantern','season','bridge','fable'])[1 + (i * 7) % 12] ||
       CASE WHEN i % 3 = 0 THEN ', volume ' || (i % 5 + 1) ELSE '' END),
       1 + i % 8, round((6 + (i * 37) % 30 + (i % 4) * 0.25)::numeric, 2), i % 9 <> 0,
       (ARRAY['hardback','paperback','ebook'])[1 + i % 3]::book_format, date '2010-01-01' + (i * 13) % 5400,
       ARRAY[(ARRAY['fiction','nature','food','history','craft','travel'])[1 + i % 6]], jsonb_build_object('pages', 80 + (i * 17) % 400)
FROM generate_series(1, 190) i;
INSERT INTO customers (email, name, city, joined_at)
SELECT lower(f) || '.' || lower(l) || i || '@example.com', f || ' ' || l, (ARRAY['Leeds','Lisbon','Osaka','Lagos','Oslo','Quito','Austin','Pune'])[1 + i % 8], now() - (i || ' days')::interval
FROM (SELECT i, (ARRAY['Maya','Theo','Priya','Jonas','Amara','Luca','Hana','Sam','Ines','Kofi'])[1 + i % 10] AS f,
             (ARRAY['Okafor','Lindqvist','Sato','Moreau','Patel','Silva','Novak','Haddad','Kim','Fischer','Mensah'])[1 + (i * 7) % 11] AS l
      FROM generate_series(1, 320) i) s;
INSERT INTO orders (customer_id, status, placed_at)
SELECT (SELECT id FROM customers ORDER BY email OFFSET (i * 13) % 320 LIMIT 1), (ARRAY['shipped','shipped','paid','refunded'])[1 + i % 4]::order_status, now() - (i * 37 || ' minutes')::interval
FROM generate_series(1, 1200) i;
INSERT INTO order_items (order_id, book_id, qty) SELECT o.id, 1 + (o.id * 7 + k * 31) % 200, 1 + (o.id + k) % 3 FROM orders o, generate_series(0, 1) k ON CONFLICT DO NOTHING;
INSERT INTO reviews (book_id, stars, body) SELECT 1 + (i * 11) % 200, 1 + (i * 3) % 5, (ARRAY['Loved it.','Slow start, lovely ending.','Gift for my dad.','Not for me.','Read it twice.'])[1 + i % 5] FROM generate_series(1, 600) i;
INSERT INTO events (kind, at, payload) SELECT (ARRAY['page_view','add_to_cart','checkout','search','sign_in'])[1 + i % 5], now() - (i || ' seconds')::interval, jsonb_build_object('session', 's' || (i % 900), 'path', '/books/' || (1 + i % 200)) FROM generate_series(1, 50000) i;
INSERT INTO import_log (line) VALUES ('imported 200 books from catalogue.csv'), ('skipped 3 rows without a title');
CREATE VIEW best_sellers AS SELECT b.id, b.title, sum(oi.qty) AS sold FROM order_items oi JOIN books b ON b.id = oi.book_id GROUP BY b.id, b.title ORDER BY sold DESC;
ANALYZE;
"
api POST /v1/projects/bookshop/branches '{"name":"pr-12"}' >/dev/null

# 34 tables in a few chains and stars, for the schema diagram.
sql warehouse "
DO \$\$
DECLARE names text[] := ARRAY['regions','sites','zones','aisles','racks','bins','suppliers','supplier_contacts','products','product_variants',
  'barcodes','lots','stock','stock_moves','purchase_orders','purchase_lines','receipts','receipt_lines','customers','addresses',
  'sales_orders','sales_lines','picks','pick_lines','packages','shipments','carriers','routes','drivers','vehicles',
  'returns','return_lines','inspections','adjustments'];
  parents int[] := ARRAY[0,1,2,3,4,5,0,7,7,9,10,10,12,13,7,15,15,17,0,19,19,21,21,23,22,25,0,27,27,29,21,31,31,13];
BEGIN
  FOR i IN 1..array_length(names, 1) LOOP
    EXECUTE format('CREATE TABLE %I (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name text NOT NULL, created_at timestamptz NOT NULL DEFAULT now()%s)',
      names[i], CASE WHEN parents[i] > 0 THEN format(', %I_id bigint REFERENCES %I(id)', regexp_replace(names[parents[i]], 's\$', ''), names[parents[i]]) ELSE '' END);
  END LOOP;
END \$\$;
ALTER TABLE stock ADD COLUMN bin_id bigint REFERENCES bins(id);
ALTER TABLE picks ADD COLUMN bin_id bigint REFERENCES bins(id);
ALTER TABLE shipments ADD COLUMN route_id bigint REFERENCES routes(id);
"
echo "seeded bookshop and warehouse on $URL"
