import type { SVGProps } from "react";
type P = SVGProps<SVGSVGElement>;
export declare const IconMail: (p: P) => import("react").JSX.Element;
export declare const IconKey: (p: P) => import("react").JSX.Element;
export declare const IconPasskey: (p: P) => import("react").JSX.Element;
export declare const IconShield: (p: P) => import("react").JSX.Element;
export declare const IconAlert: (p: P) => import("react").JSX.Element;
export declare const IconCheck: (p: P) => import("react").JSX.Element;
export declare const IconChevrons: (p: P) => import("react").JSX.Element;
export declare const IconPlus: (p: P) => import("react").JSX.Element;
export declare const IconOut: (p: P) => import("react").JSX.Element;
export declare const IconCopy: (p: P) => import("react").JSX.Element;
export declare const IconLink: (p: P) => import("react").JSX.Element;
export declare const IconUsers: (p: P) => import("react").JSX.Element;
export declare const IconArrowLeft: (p: P) => import("react").JSX.Element;
export declare const IconGoogle: (p: P) => import("react").JSX.Element;
export declare const IconGitHub: (p: P) => import("react").JSX.Element;
export {};
