import postgres from "postgres";

// postgres.js runs on Node.js and on Bun. It reads DATABASE_URL, which Tiffin
// sets when the project has Postgres.
export const sql = postgres(process.env.DATABASE_URL ?? "", { max: 5 });

export type Note = { id: number; text: string; created_at: string };

let ready: Promise<unknown> | undefined;

// Creates the table once per process. Idempotent, so every deploy can run it,
// and serialized with an advisory lock so instances don't race.
export function migrate() {
  ready ??= sql
    .begin(async (tx) => {
      await tx`select pg_advisory_xact_lock(hashtext('nuxt-notes-migrate'))`;
      await tx`create table if not exists notes (
        id integer generated by default as identity primary key,
        text text not null check (length(text) between 1 and 280),
        created_at timestamptz not null default now()
      )`;
    })
    .catch((err: unknown) => {
      ready = undefined;
      throw err;
    });
  return ready;
}
