// Code generated by packages/emails (bun run build). DO NOT EDIT.
// The templates are React Email components in packages/emails/src/emails.

package templates

import "fmt"

// AlertData fills alert: An alert: firing, resolved, or a test of alert delivery.
type AlertData struct {
	Brand       string // "ShipTiffin" on shiptiffin.com, "Tiffin" on a self-hosted box
	Host        string // The dashboard's host, e.g. dashboard.example.com
	MarkURL     string // The mark as a PNG (email-mark.png on the dashboard); empty for none
	State       string // What happened: firing, resolved, test
	Box         string // The box's name or domain
	Rule        string // The rule: "disk-space"
	Summary     string // One sentence: "/ is 92% full (limit 90%)"
	Watching    string // What the rule watches: "/", "project:shop"; empty to leave it out
	Value       string // The reading: "92 (limit 90)"; empty to leave it out
	When        string // "7 October 2026, 14:32 UTC"
	Description string // The rule's description; empty to leave it out
	URL         string // The dashboard; empty for no button
}

// Alert renders alert: An alert: firing, resolved, or a test of alert delivery.
func Alert(d AlertData) (*Email, error) {
	switch d.State {
	case "firing", "resolved", "test":
	default:
		return nil, fmt.Errorf("alert: State is %q, want one of firing, resolved, test", d.State)
	}
	return render("alert", d)
}

// InviteData fills invite: Invite to a box: a new person's first sign-in link.
type InviteData struct {
	Brand   string // "ShipTiffin" on shiptiffin.com, "Tiffin" on a self-hosted box
	Host    string // The dashboard's host, e.g. dashboard.example.com
	MarkURL string // The mark as a PNG (email-mark.png on the dashboard); empty for none
	First   string // First name, or "there"
	By      string // Who invited them: a name, or "The box's owner"
	Role    string // Their role on the box: owner, admin, member, viewer
	URL     string // The one-time sign-in link
	Until   string // How long the link works: "for the next 30 minutes", "until 13 October 2026, 21:05 UTC"
}

// Invite renders invite: Invite to a box: a new person's first sign-in link.
func Invite(d InviteData) (*Email, error) {
	switch d.Role {
	case "owner", "admin", "member", "viewer":
	default:
		return nil, fmt.Errorf("invite: Role is %q, want one of owner, admin, member, viewer", d.Role)
	}
	return render("invite", d)
}

// LinkData fills link: A fresh sign-in link an admin made for someone.
type LinkData struct {
	Brand   string // "ShipTiffin" on shiptiffin.com, "Tiffin" on a self-hosted box
	Host    string // The dashboard's host, e.g. dashboard.example.com
	MarkURL string // The mark as a PNG (email-mark.png on the dashboard); empty for none
	First   string // First name, or "there"
	By      string // Who made the link: a name, or "The box's owner"
	URL     string // The one-time sign-in link
	Until   string // How long the link works: "for the next 30 minutes"
}

// Link renders link: A fresh sign-in link an admin made for someone.
func Link(d LinkData) (*Email, error) {
	return render("link", d)
}

// NewKeyData fills new-key: Someone created an API key in the dashboard (sent to them).
type NewKeyData struct {
	Brand      string // "ShipTiffin" on shiptiffin.com, "Tiffin" on a self-hosted box
	Host       string // The dashboard's host, e.g. dashboard.example.com
	MarkURL    string // The mark as a PNG (email-mark.png on the dashboard); empty for none
	First      string // First name; empty when the box doesn't know it
	By         string // Who created it: "Sam Rivera"
	Name       string // The key's name: "ci"
	Access     string // What it can do, in words: "Full access to all projects (admin)", "Read only: shop, blog"
	Expires    string // "Never", "6 January 2027"
	When       string // "Wednesday 7 October, 14:32 UTC"
	Device     string // The browser it was made in: "Chrome on macOS"; empty when unknown
	Where      string // The country the address is in, "United States"; empty when unknown
	IP         string // The address it came from; empty to leave it out
	URL        string // The dashboard's API keys page; empty for no button
	ShownURL   string // The same address without https://: "dashboard.example.com/settings/keys"
	SignInsURL string // Their sign-ins page (to sign out everywhere else); empty for none
}

// NewKey renders new-key: Someone created an API key in the dashboard (sent to them).
func NewKey(d NewKeyData) (*Email, error) {
	return render("new-key", d)
}

// NewPasskeyData fills new-passkey: A passkey was added to someone's sign-ins (sent to them).
type NewPasskeyData struct {
	Brand      string // "ShipTiffin" on shiptiffin.com, "Tiffin" on a self-hosted box
	Host       string // The dashboard's host, e.g. dashboard.example.com
	MarkURL    string // The mark as a PNG (email-mark.png on the dashboard); empty for none
	First      string // First name; empty when the box doesn't know it
	Name       string // The passkey's name: "MacBook"
	When       string // "Wednesday 7 October, 14:32 UTC"
	Device     string // The browser it was added in: "Chrome on macOS"; empty when unknown
	Where      string // The country the address is in, "United States"; empty when unknown
	IP         string // The address it came from; empty to leave it out
	URL        string // Their passkeys page in the dashboard; empty for no button
	ShownURL   string // The same address without https://: "dashboard.example.com/settings/passkeys"
	SignInsURL string // Their sign-ins page (to sign out everywhere else); empty for none
}

// NewPasskey renders new-passkey: A passkey was added to someone's sign-ins (sent to them).
func NewPasskey(d NewPasskeyData) (*Email, error) {
	return render("new-passkey", d)
}

// NewSignInData fills new-sign-in: Someone signed in from a browser the box hasn't seen them use.
type NewSignInData struct {
	Brand       string // "ShipTiffin" on shiptiffin.com, "Tiffin" on a self-hosted box
	Host        string // The dashboard's host, e.g. dashboard.example.com
	MarkURL     string // The mark as a PNG (email-mark.png on the dashboard); empty for none
	First       string // First name; empty when the box doesn't know it
	Device      string // "Chrome on macOS"
	From        string // The device inside a sentence, for the subject: "Chrome on macOS", "an unknown browser"
	When        string // "Wednesday 7 October, 14:32 UTC"
	How         string // "Google", "GitHub", "Passkey", "Sign-in link"
	Where       string // The country the address is in, "United States"; empty when unknown
	IP          string // The address it came from; empty to leave it out
	Admin       bool   // An owner or admin: they can revoke API keys themselves
	URL         string // Their sign-ins page in the dashboard (where they can sign out everywhere else); empty for no button
	ShownURL    string // The same address without https://, to show under the button: "dashboard.example.com/settings/sign-ins"
	PasskeysURL string // Their passkeys page in the dashboard; empty for none
	KeysURL     string // The dashboard's API keys page (owners and admins); empty for none
}

// NewSignIn renders new-sign-in: Someone signed in from a browser the box hasn't seen them use.
func NewSignIn(d NewSignInData) (*Email, error) {
	return render("new-sign-in", d)
}

// PasskeyRemovedData fills passkey-removed: A passkey was removed from someone's sign-ins (sent to them).
type PasskeyRemovedData struct {
	Brand      string // "ShipTiffin" on shiptiffin.com, "Tiffin" on a self-hosted box
	Host       string // The dashboard's host, e.g. dashboard.example.com
	MarkURL    string // The mark as a PNG (email-mark.png on the dashboard); empty for none
	First      string // First name; empty when the box doesn't know it
	Name       string // The passkey's name: "MacBook"
	When       string // "Wednesday 7 October, 14:32 UTC"
	Device     string // The browser it was removed in: "Chrome on macOS"; empty when unknown
	Where      string // The country the address is in, "United States"; empty when unknown
	IP         string // The address it came from; empty to leave it out
	URL        string // Their passkeys page in the dashboard; empty for no button
	ShownURL   string // The same address without https://: "dashboard.example.com/settings/passkeys"
	SignInsURL string // Their sign-ins page (to sign out everywhere else); empty for none
}

// PasskeyRemoved renders passkey-removed: A passkey was removed from someone's sign-ins (sent to them).
func PasskeyRemoved(d PasskeyRemovedData) (*Email, error) {
	return render("passkey-removed", d)
}

// RelayTestData fills relay-test: The test email from Settings › Email (tiffin email relay test).
type RelayTestData struct {
	Brand   string // "ShipTiffin" on shiptiffin.com, "Tiffin" on a self-hosted box
	Host    string // The dashboard's host, e.g. dashboard.example.com
	MarkURL string // The mark as a PNG (email-mark.png on the dashboard); empty for none
	Relay   string // The mail service: "Resend", "Postmark", "smtp.example.com"
	From    string // The sender it went out as
	When    string // "7 October 2026, 14:32 UTC"
}

// RelayTest renders relay-test: The test email from Settings › Email (tiffin email relay test).
func RelayTest(d RelayTestData) (*Email, error) {
	return render("relay-test", d)
}

// SignInData fills sign-in: The link someone asked for with "Email me a sign-in link".
type SignInData struct {
	Brand   string // "ShipTiffin" on shiptiffin.com, "Tiffin" on a self-hosted box
	Host    string // The dashboard's host, e.g. dashboard.example.com
	MarkURL string // The mark as a PNG (email-mark.png on the dashboard); empty for none
	First   string // First name, or "there"
	URL     string // The one-time sign-in link
	Until   string // How long the link works: "for the next 15 minutes"
	IP      string // The address the request came from; empty to leave it out
}

// SignIn renders sign-in: The link someone asked for with "Email me a sign-in link".
func SignIn(d SignInData) (*Email, error) {
	return render("sign-in", d)
}

// Names lists every box email.
var Names = []string{"alert", "invite", "link", "new-key", "new-passkey", "new-sign-in", "passkey-removed", "relay-test", "sign-in"}
