// Code generated by packages/emails (bun run build). DO NOT EDIT.
// The templates are React Email components in packages/emails/src/emails.

package templates

import "fmt"

// AlertData fills alert: An alert: firing, resolved, or a test of alert delivery.
type AlertData struct {
	Brand       string // "ShipTiffin" on shiptiffin.com, "Tiffin" on a self-hosted box
	Host        string // The dashboard's host, e.g. dashboard.example.com
	MarkURL     string // The mark as a PNG (email-mark.png on the dashboard); empty for none
	State       string // What happened: firing, resolved, test
	Box         string // The box's name or domain
	Rule        string // The rule: "disk-space"
	Summary     string // One sentence: "/ is 92% full (limit 90%)"
	Watching    string // What the rule watches: "/", "project:shop"; empty to leave it out
	Value       string // The reading: "92 (limit 90)"; empty to leave it out
	When        string // "7 October 2026, 14:32 UTC"
	Description string // The rule's description; empty to leave it out
	URL         string // The dashboard; empty for no button
}

// Alert renders alert: An alert: firing, resolved, or a test of alert delivery.
func Alert(d AlertData) (*Email, error) {
	switch d.State {
	case "firing", "resolved", "test":
	default:
		return nil, fmt.Errorf("alert: State is %q, want one of firing, resolved, test", d.State)
	}
	return render("alert", d)
}

// InviteData fills invite: Invite to a box: a new person's first sign-in link.
type InviteData struct {
	Brand   string // "ShipTiffin" on shiptiffin.com, "Tiffin" on a self-hosted box
	Host    string // The dashboard's host, e.g. dashboard.example.com
	MarkURL string // The mark as a PNG (email-mark.png on the dashboard); empty for none
	First   string // First name, or "there"
	By      string // Who invited them: a name, or "The box's owner"
	Role    string // Their role on the box: owner, admin, member, viewer
	URL     string // The one-time sign-in link
	Until   string // How long the link works: "for the next 30 minutes", "until 13 October 2026, 21:05 UTC"
}

// Invite renders invite: Invite to a box: a new person's first sign-in link.
func Invite(d InviteData) (*Email, error) {
	switch d.Role {
	case "owner", "admin", "member", "viewer":
	default:
		return nil, fmt.Errorf("invite: Role is %q, want one of owner, admin, member, viewer", d.Role)
	}
	return render("invite", d)
}

// LinkData fills link: A fresh sign-in link an admin made for someone.
type LinkData struct {
	Brand   string // "ShipTiffin" on shiptiffin.com, "Tiffin" on a self-hosted box
	Host    string // The dashboard's host, e.g. dashboard.example.com
	MarkURL string // The mark as a PNG (email-mark.png on the dashboard); empty for none
	First   string // First name, or "there"
	By      string // Who made the link: a name, or "The box's owner"
	URL     string // The one-time sign-in link
	Until   string // How long the link works: "for the next 30 minutes"
}

// Link renders link: A fresh sign-in link an admin made for someone.
func Link(d LinkData) (*Email, error) {
	return render("link", d)
}

// NewSignInData fills new-sign-in: Someone signed in from a browser the box hasn't seen them use.
type NewSignInData struct {
	Brand   string // "ShipTiffin" on shiptiffin.com, "Tiffin" on a self-hosted box
	Host    string // The dashboard's host, e.g. dashboard.example.com
	MarkURL string // The mark as a PNG (email-mark.png on the dashboard); empty for none
	First   string // First name, or "there"
	Device  string // "Chrome on macOS"
	When    string // "7 October 2026, 14:32 UTC"
	Via     string // "a sign-in link", "a passkey"
	IP      string // The address it came from; empty to leave it out
	Owner   bool   // They own the box (what to do if it wasn't them differs)
	URL     string // Where to check sign-ins and keys (the dashboard's Settings); empty for no button
}

// NewSignIn renders new-sign-in: Someone signed in from a browser the box hasn't seen them use.
func NewSignIn(d NewSignInData) (*Email, error) {
	return render("new-sign-in", d)
}

// RelayTestData fills relay-test: The test email from Settings › Email (tiffin email relay test).
type RelayTestData struct {
	Brand   string // "ShipTiffin" on shiptiffin.com, "Tiffin" on a self-hosted box
	Host    string // The dashboard's host, e.g. dashboard.example.com
	MarkURL string // The mark as a PNG (email-mark.png on the dashboard); empty for none
	Relay   string // The mail service: "Resend", "Postmark", "smtp.example.com"
	From    string // The sender it went out as
	When    string // "7 October 2026, 14:32 UTC"
}

// RelayTest renders relay-test: The test email from Settings › Email (tiffin email relay test).
func RelayTest(d RelayTestData) (*Email, error) {
	return render("relay-test", d)
}

// SignInData fills sign-in: The link someone asked for with "Email me a sign-in link".
type SignInData struct {
	Brand   string // "ShipTiffin" on shiptiffin.com, "Tiffin" on a self-hosted box
	Host    string // The dashboard's host, e.g. dashboard.example.com
	MarkURL string // The mark as a PNG (email-mark.png on the dashboard); empty for none
	First   string // First name, or "there"
	URL     string // The one-time sign-in link
	Until   string // How long the link works: "for the next 15 minutes"
	IP      string // The address the request came from; empty to leave it out
}

// SignIn renders sign-in: The link someone asked for with "Email me a sign-in link".
func SignIn(d SignInData) (*Email, error) {
	return render("sign-in", d)
}

// Names lists every box email.
var Names = []string{"alert", "invite", "link", "new-sign-in", "relay-test", "sign-in"}
