// Code generated by packages/emails (bun run build). DO NOT EDIT.

package templates

var samples = map[string]func() (*Email, error){
	"alert": func() (*Email, error) {
		return Alert(AlertData{
			Brand:       "ShipTiffin",
			Host:        "dashboard.shiptiffin.com",
			MarkURL:     "https://dashboard.shiptiffin.com/email-mark.png",
			State:       "firing",
			Box:         "shiptiffin.com",
			Rule:        "disk-space",
			Summary:     "/ is 92% full (the limit is 90%).",
			Watching:    "/",
			Value:       "92% (limit 90%)",
			When:        "7 October 2026, 14:32 UTC",
			Description: "Warns before the disk fills up and the box stops accepting writes.",
			URL:         "https://dashboard.shiptiffin.com/observe",
		})
	},
	"invite": func() (*Email, error) {
		return Invite(InviteData{
			Brand:   "ShipTiffin",
			Host:    "dashboard.shiptiffin.com",
			MarkURL: "https://dashboard.shiptiffin.com/email-mark.png",
			First:   "Sam",
			By:      "Bilal Tahir",
			Role:    "member",
			URL:     "https://dashboard.shiptiffin.com/login#inv_7Hk2pQ9xW",
			Until:   "until 9 October 2026, 18:00 UTC",
		})
	},
	"link": func() (*Email, error) {
		return Link(LinkData{
			Brand:   "ShipTiffin",
			Host:    "dashboard.shiptiffin.com",
			MarkURL: "https://dashboard.shiptiffin.com/email-mark.png",
			First:   "Sam",
			By:      "Bilal Tahir",
			URL:     "https://dashboard.shiptiffin.com/login#lnk_4Rt8sV2mQ",
			Until:   "for the next 30 minutes",
		})
	},
	"new-key": func() (*Email, error) {
		return NewKey(NewKeyData{
			Brand:      "ShipTiffin",
			Host:       "dashboard.shiptiffin.com",
			MarkURL:    "https://dashboard.shiptiffin.com/email-mark.png",
			First:      "Sam",
			By:         "Sam Rivera",
			Name:       "ci",
			Access:     "Full access to all projects (admin)",
			Expires:    "Never",
			When:       "Wednesday 7 October, 14:32 UTC",
			Device:     "Chrome on macOS",
			Where:      "United Kingdom",
			IP:         "198.51.100.7",
			URL:        "https://dashboard.shiptiffin.com/settings/keys",
			ShownURL:   "dashboard.shiptiffin.com/settings/keys",
			SignInsURL: "https://dashboard.shiptiffin.com/settings/sign-ins",
		})
	},
	"new-sign-in": func() (*Email, error) {
		return NewSignIn(NewSignInData{
			Brand:       "ShipTiffin",
			Host:        "dashboard.shiptiffin.com",
			MarkURL:     "https://dashboard.shiptiffin.com/email-mark.png",
			First:       "Sam",
			Device:      "Safari on iPhone",
			From:        "Safari on iPhone",
			When:        "Wednesday 7 October, 14:32 UTC",
			How:         "Passkey",
			Where:       "United Kingdom",
			IP:          "198.51.100.7",
			Admin:       true,
			URL:         "https://dashboard.shiptiffin.com/settings/sign-ins",
			ShownURL:    "dashboard.shiptiffin.com/settings/sign-ins",
			PasskeysURL: "https://dashboard.shiptiffin.com/settings/passkeys",
			KeysURL:     "https://dashboard.shiptiffin.com/settings/keys",
		})
	},
	"relay-test": func() (*Email, error) {
		return RelayTest(RelayTestData{
			Brand:   "ShipTiffin",
			Host:    "dashboard.shiptiffin.com",
			MarkURL: "https://dashboard.shiptiffin.com/email-mark.png",
			Relay:   "Resend",
			From:    "ShipTiffin <hello@shiptiffin.com>",
			When:    "7 October 2026, 14:32 UTC",
		})
	},
	"sign-in": func() (*Email, error) {
		return SignIn(SignInData{
			Brand:   "ShipTiffin",
			Host:    "dashboard.shiptiffin.com",
			MarkURL: "https://dashboard.shiptiffin.com/email-mark.png",
			First:   "Sam",
			URL:     "https://dashboard.shiptiffin.com/login#eml_9Qw3zL6pK",
			Until:   "for the next 15 minutes",
			IP:      "203.0.113.24",
		})
	},
}
