import postgres from "postgres";

// Postgres through the box's connection pooler (DATABASE_URL, set by Tiffin).
// prepare: false because the pooler runs in transaction mode, where
// postgres.js's prepared statements can misbehave (docs/guide/data.md).
// One small pool per process, kept on globalThis so `bun --hot` reuses it
// instead of opening another.
const g = globalThis as { __sql?: postgres.Sql };
export const sql = (g.__sql ??= postgres(process.env.DATABASE_URL ?? "", { prepare: false, max: 5, idle_timeout: 20 }));

// Creates the table on a direct connection (schema changes skip the pooler).
// Idempotent, so every deploy can run it, and serialized with an advisory
// lock so instances starting together do not race.
export async function migrate() {
  const direct = postgres(process.env.DIRECT_DATABASE_URL || process.env.DATABASE_URL || "", { max: 1, onnotice: () => {} });
  try {
    await direct.begin(async (tx) => {
      await tx`select pg_advisory_xact_lock(hashtext('guestbook-migrate'))`;
      await tx`create table if not exists entries (
        id integer generated by default as identity primary key,
        name text not null check (length(name) between 1 and 60),
        message text not null check (length(message) between 1 and 280),
        created_at timestamptz not null default now()
      )`;
    });
  } finally {
    await direct.end();
  }
}
