import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { POSTS, PRODUCTS } from "./content";
import { sql } from "./db";

/**
 * Creates the tables and the seed rows, and puts the featured image in the
 * media bucket. Safe to run on every start: instances take turns through an
 * advisory lock and existing rows are left alone.
 */
export async function seed() {
  const db = sql();
  await db.begin(async (tx) => {
    await tx`select pg_advisory_xact_lock(hashtext('next-showcase-seed'))`;
    await tx`create table if not exists products (
      id int primary key, slug text unique not null, name text not null,
      price int not null, stock int not null, likes int not null default 0)`;
    await tx`create table if not exists posts (
      slug text primary key, title text not null, body text not null, rev int not null default 1)`;
    await tx`create table if not exists orders (
      id int primary key, product_id int not null references products(id),
      qty int not null, created_at timestamptz not null)`;
    await tx`create table if not exists notes (
      id int generated by default as identity primary key,
      text text not null check (length(text) between 1 and 280),
      created_at timestamptz not null default now())`;
    await tx`insert into products ${tx(PRODUCTS, "id", "slug", "name", "price", "stock", "likes")} on conflict (id) do nothing`;
    await tx`insert into posts ${tx(POSTS, "slug", "title", "body", "rev")} on conflict (slug) do nothing`;
    // 500 orders spread over the last 30 days, the same on every box.
    await tx`insert into orders (id, product_id, qty, created_at)
      select g, 1 + (g * 7) % ${PRODUCTS.length}, 1 + g % 3, now() - (g * interval '86 minutes')
      from generate_series(1, 500) g on conflict (id) do nothing`;
  });
  await seedBucket();
}

// Bun.s3 reads the project's S3_* variables. Under Node.js the image is left
// to a Bun deploy (the bench deploys on Bun first).
async function seedBucket() {
  const s3 = (globalThis as { Bun?: { s3?: BunS3 } }).Bun?.s3;
  const bucket = process.env.S3_BUCKET_MEDIA;
  if (!s3 || !bucket) {
    console.log("[showcase] seed: skipping the bucket image (needs Bun.s3 and S3_BUCKET_MEDIA)");
    return;
  }
  const file = s3.file("featured.jpg", { bucket });
  if (await file.exists()) return;
  const bytes = await readFile(join(process.cwd(), "seed", "featured.jpg"));
  await file.write(bytes, { type: "image/jpeg" });
  console.log("[showcase] seed: uploaded featured.jpg to " + bucket);
}

type BunS3 = {
  file(key: string, opts: { bucket: string }): {
    exists(): Promise<boolean>;
    write(data: Uint8Array, opts: { type: string }): Promise<number>;
  };
};
