// On the box the app runs on Bun, which has a Postgres client built in
// (Bun.sql). On Node.js (runtime: "node"), postgres.js gives the same API.
// Both read DATABASE_URL, which Tiffin sets. Locally, run `bun run dev` with
// it set.
import postgres from "postgres";

type Sql = ReturnType<typeof postgres>;
let pg: Sql | undefined;

export function db(): Sql {
  const bun = (globalThis as { Bun?: { sql: Sql } }).Bun;
  if (bun) return bun.sql;
  pg ??= postgres(process.env.DATABASE_URL!);
  return pg;
}

let ready: Promise<unknown> | undefined;

// Creates the table once per process. Idempotent, so every deploy can run it,
// and serialized with an advisory lock so instances do not race.
export function migrate() {
  ready ??= db()
    .begin(async (tx) => {
      await tx`select pg_advisory_xact_lock(hashtext('start-notes-migrate'))`;
      await tx`create table if not exists notes (
        id integer generated by default as identity primary key,
        text text not null check (length(text) between 1 and 280),
        created_at timestamptz not null default now()
      )`;
    })
    .catch((err) => {
      ready = undefined;
      throw err;
    });
  return ready;
}
