// Bun has a Postgres client built in (Bun.SQL): the server needs no driver.
// It reads DATABASE_URL, which Tiffin sets when the project has Postgres.
export const sql = new Bun.SQL(process.env.DATABASE_URL ?? "");

export type Note = { id: number; text: string; created_at: string };

let ready: Promise<unknown> | undefined;

// Creates the table once per process. Idempotent, so every deploy can run it,
// and serialized with an advisory lock so instances don't race.
export function migrate() {
  ready ??= sql
    .begin(async (tx) => {
      await tx`select pg_advisory_xact_lock(hashtext('rr-notes-migrate'))`;
      await tx`create table if not exists notes (
        id integer generated by default as identity primary key,
        text text not null check (length(text) between 1 and 280),
        created_at timestamptz not null default now()
      )`;
    })
    .catch((err: unknown) => {
      ready = undefined;
      throw err;
    });
  return ready;
}
